services:
  - type: worker
    plan: free
    name: ğŒğğ­ğšğŒğ¨ğ«ğ©ğ¡ğğ«
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Aluval/MetaMorpher.git
    branch: SH24BOTS-PVT
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      
